name: Docker Build and Push

on:
  push:
    branches:
      - main  # Run this workflow on any push to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use GitHub Secrets for Docker credentials
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t sakshi2s2/devopsassignment-backend:latest .
          docker push sakshi2s2/devopsassignment-backend:latest
